### ISSUE TITLE
Thanks for the great project!

### ISSUE THREAD

**Issue by Shayan-To** [western/http-up#1]
I was searching for a long while for exactly this, and couldn't find anything useful, until I saw this gem!

Thanks for bringing this project to life!

I'm an experienced font-end/TS developer. Although I'm not anything like fast to respond(!), but I'll try to do my best if this needed any help.

**Comment by western** [comment]
> I was searching for a long while for exactly this, and couldn't find anything useful, until I saw this gem!
> 
> Thanks for bringing this project to life!
> 
> I'm an experienced font-end/TS developer. Although I'm not anything like fast to respond(!), but I'll try to do my best if this needed any help.

Thank you for feedback!

This NPM Package was written for the same reason. I was looking for some package, but decided to write it.

For future versions i think need some roadmap or feature list, or Issues in github.

**Comment by western** [comment]
@Shayan-To, good evening!

i added you as collaborators, if you do not mind.

sorry, but i still work in chaotic mode.
and ideas come to me suddenly and i already wrote something.

what you think what is primary problem of project?

i think it maybe security and tests. 
i already wrote analogue project in golang (http-here) and trying to be there and here.

i still think that i not want rich frontend (not react or not vue).
what you think about it?
